import { Profile } from "./types";

export const mockProfiles: Profile[] = [
  {
    id: "p1",
    name: "Jayden M.",
    ageBand: "16-17",
    sport: "Baseball",
    focus: "Long toss",
    skillLevel: "Varsity+",
    city: "Round Rock",
    state: "TX",
    distanceMiles: 2.4,
    bio: "Varsity pitcher trying to add velocity before fall ball. Looking for someone to stretch out long toss with 3-4x a week.",
    initials: "JM",
    guardianVerified: true,
  },
  {
    id: "p2",
    name: "Marcus T.",
    ageBand: "16-17",
    sport: "Baseball",
    focus: "Long toss",
    skillLevel: "Competitive",
    city: "Round Rock",
    state: "TX",
    distanceMiles: 3.1,
    bio: "Sophomore, play travel ball. Want a regular throwing partner to build arm strength for next season.",
    initials: "MT",
    guardianVerified: true,
  },
  {
    id: "p3",
    name: "Ava R.",
    ageBand: "13-15",
    sport: "Softball",
    focus: "Fielding & throwing accuracy",
    skillLevel: "Rec / casual",
    city: "Cedar Park",
    state: "TX",
    distanceMiles: 5.6,
    bio: "8th grade, play rec league. Would love a weekend partner for grounders and throw-downs.",
    initials: "AR",
    guardianVerified: true,
  },
  {
    id: "p4",
    name: "Diego S.",
    ageBand: "13-15",
    sport: "Basketball",
    focus: "Ball handling & shooting reps",
    skillLevel: "Competitive",
    city: "Austin",
    state: "TX",
    distanceMiles: 4.2,
    bio: "Guard trying to make the JV squad next year. Looking for someone to run drills and get up shots with after school.",
    initials: "DS",
    guardianVerified: false,
  },
  {
    id: "p5",
    name: "Sophia L.",
    ageBand: "16-17",
    sport: "Tennis",
    focus: "Baseline rallying",
    skillLevel: "Varsity+",
    city: "Austin",
    state: "TX",
    distanceMiles: 6.8,
    bio: "Varsity #2 singles. Need a consistent hitting partner for baseline rallies before matches start up.",
    initials: "SL",
    guardianVerified: true,
  },
  {
    id: "p6",
    name: "Chris P.",
    ageBand: "25-34",
    sport: "Baseball",
    focus: "Long toss",
    skillLevel: "Rec / casual",
    city: "Round Rock",
    state: "TX",
    distanceMiles: 1.9,
    bio: "Played through college, haven't picked up a ball in years. Would love to get the arm loose again and maybe join a men's league.",
    initials: "CP",
  },
  {
    id: "p7",
    name: "Brianna K.",
    ageBand: "18-24",
    sport: "Soccer",
    focus: "Finishing & footwork drills",
    skillLevel: "Competitive",
    city: "Georgetown",
    state: "TX",
    distanceMiles: 8.3,
    bio: "Ex-club player, home from college for the summer. Looking for pickup partners for finishing drills a couple times a week.",
    initials: "BK",
  },
  {
    id: "p8",
    name: "Omar H.",
    ageBand: "35+",
    sport: "Basketball",
    focus: "Shooting reps",
    skillLevel: "Rec / casual",
    city: "Austin",
    state: "TX",
    distanceMiles: 3.5,
    bio: "Weekend warrior trying to relive some glory days. Just want steady reps and someone to rebound for.",
    initials: "OH",
  },
  {
    id: "p9",
    name: "Nate W.",
    ageBand: "18-24",
    sport: "Football",
    focus: "Route running",
    skillLevel: "Competitive",
    city: "Pflugerville",
    state: "TX",
    distanceMiles: 7.0,
    bio: "Former high school WR, staying sharp for adult flag league. Need a QB or another WR to run routes with.",
    initials: "NW",
  },
  {
    id: "p10",
    name: "Isabella C.",
    ageBand: "13-15",
    sport: "Track & Field",
    focus: "Sprint starts & block work",
    skillLevel: "Rec / casual",
    city: "Cedar Park",
    state: "TX",
    distanceMiles: 4.9,
    bio: "Middle schooler working on my 100m. Looking for a training partner to push my starts.",
    initials: "IC",
    guardianVerified: true,
  },
  {
    id: "p11",
    name: "Tyler B.",
    ageBand: "16-17",
    sport: "Baseball",
    focus: "Bullpen sessions",
    skillLevel: "Varsity+",
    city: "Georgetown",
    state: "TX",
    distanceMiles: 9.1,
    bio: "Varsity pitcher, need a catcher for bullpens twice a week leading into the season.",
    initials: "TB",
    guardianVerified: true,
  },
  {
    id: "p12",
    name: "Grace F.",
    ageBand: "25-34",
    sport: "Tennis",
    focus: "Baseline rallying",
    skillLevel: "Rec / casual",
    city: "Austin",
    state: "TX",
    distanceMiles: 2.2,
    bio: "Getting back into tennis after a long break. Looking for a casual rally partner, no pressure.",
    initials: "GF",
  },
];
